### ISSUE TITLE
Gage TODO

### ISSUE THREAD

**Issue by gclawson1** [Panga-Watch/Communication-and-Issues#3]
- [ ] help team with Objectives, Significance, and Deliverables which are due Friday, April 19
- [ ] read over data management slides sent by Sean
- [ ] begin literature review for technology adoption in SSF/small communities
- [ ] read through email from Gavin McDonald
